apiVersion: v1
kind: Namespace
metadata:
  name: demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: hello-node
          ports:
            - containerPort: 3000
              name: http
          image: karimniang/hello-word-img
---
apiVersion: v1
kind: Service
metadata:
  name: demo-entrypoint
  namespace: demo
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - port: 3000
      targetPort: 3000
      #name: name-of-service-port
      #protocol: TCP
  #externalTrafficPolicy: Local
